name: "go-licenses"
author: "Syu-fu"
description: "Check go-licenses"

branding:
  icon: package
  color: blue

runs:
  using: composite
  steps:
    - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
      with:
        go-version: "1.22"

    - run: go install github.com/google/go-licenses@latest
      shell: bash

    - name: Check licenses
      run: go-licenses check ./...
      shell: bash

    - name: Get licenses list
      run: go-licenses csv ./...
      shell: bash
