name: "go-licenses"
author: "Syu-fu"
description: "Check go-licenses"

branding:
  icon: package
  color: blue

runs:
  using: composite
  steps:
    - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
      with:
        go-version: "1.22"

    - run: go install github.com/google/go-licenses@latest
      shell: bash

    - name: Check licenses
      run: go-licenses check ./...
      shell: bash

    - name: Get licenses list
      run: go-licenses csv ./...
      shell: bash
