name: "go-licenses"
author: "Syu-fu"
description: "Check go-licenses"

branding:
  icon: package
  color: blue

runs:
  using: composite
  steps:
    - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
      with:
        go-version: "1.22"

    - run: go install github.com/google/go-licenses@latest
      shell: bash

    - name: Check licenses
      run: go-licenses check ./...
      shell: bash

    - name: Get licenses list
      run: go-licenses csv ./...
      shell: bash
